/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "bootloader.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(BootloaderRequest, BootloaderRequest, 2)


PB_BIND(BootloaderResponse, BootloaderResponse, AUTO)


PB_BIND(HandshakeRequest, HandshakeRequest, AUTO)


PB_BIND(HandshakeResponse, HandshakeResponse, AUTO)


PB_BIND(DataPacket, DataPacket, 2)


PB_BIND(FlashProgramRequest, FlashProgramRequest, AUTO)


PB_BIND(FlashProgramResponse, FlashProgramResponse, AUTO)


PB_BIND(ErrorRecoveryRequest, ErrorRecoveryRequest, AUTO)


PB_BIND(ErrorReport, ErrorReport, AUTO)


PB_BIND(Acknowledgment, Acknowledgment, AUTO)









